spring:
  config:
    import: optional:classpath:application-secrets.properties

server: 
  port: 8443 
  ssl: 
    enabled: true 
    key-store: ${server.ssl.key-store} 
    key-store-password: ${server.ssl.key-store-password}
    key-store-type: PKCS12 
  http2: 
    enabled: true